services:
  postgres_main:
    container_name: postgres_main
    image: postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-replica:/var/lib/postgresql/data-replica
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql

  postgres_replica:
    container_name: postgres_replica
    image: postgres:15
    restart: always
    volumes:
      - ./data-replica:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
